### ISSUE TITLE
Latest nnutils with cuda 10.1 

### ISSUE THREAD

**Issue by vbosch** [jpuigcerver/nnutils#1]
Hi,

When compiling current nnutils with the latest torch (1.4) and torchvision  (0.5.0) with CUDA 10.1 I get the following error when running the tests:

python -m unittest nnutils_pytorch.adaptive_avgpool_2d_test
E
======================================================================
ERROR: nnutils_pytorch (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: nnutils_pytorch
Traceback (most recent call last):
  File "/home/prhlt/anaconda3/envs/KWS/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/prhlt/anaconda3/envs/KWS/lib/python3.6/site-packages/nnutils_pytorch/__init__.py", line 3, in <module>
    import nnutils_pytorch._C as _nnutils_pytorch
ImportError: /home/prhlt/anaconda3/envs/KWS/lib/python3.6/site-packages/nnutils_pytorch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeM$
taDataInstance_preallocated_29E
----------------------------------------------------------------------
Ran 1 test in 0.000s
FAILED (errors=1)

I came upon this error when trying to perform a clean install of PyLaia with CUDA 10.1.  Everything works fine with the latest versions of all libraries except the adaptive_pooling functionality for model creation that depends on nnutils.

The create model issue does not happen with 
    - nnutils-pytorch==0.4.0
    - torch==1.1.0
    - torchvision==0.3.0
 
But then the old pytorch has issues with CUDA 10.1 when training.

Is there a plan to update this or should I downgrade to CUDA 10.0? 

Thank you for your time :-)

**Comment by jpuigcerver** [comment]
Yes. I was notified by travis a few days ago, but I haven't had time to fix it yet. 

After ICML deadline (tomorrow), I'll make some time to fix it.

**Comment by jpuigcerver** [comment]
FYI: I'm still working on this. My personal workstation was not very updated and I had to do a bunch of things to upgrade to Cuda 10.1...

**Comment by jpuigcerver** [comment]
I've uploaded version 0.6.0.post1 to PyPI. It works with PyTorch 1.4.0 & Cuda 10.1.
