### ISSUE TITLE
Support C++14 Compiler

### ISSUE THREAD

**Issue by oliveirasecacc** [jpuigcerver/nnutils#2]
While I was trying to update the code to work with Pytorch 1.5, one of the errors I received when building the pytorch extension was "#error You need C++14 to compile PyTorch". After modifying the following code in setup.py
`extra_compile_args = {`
`    "cxx": ["-std=c++14", "-O3", "-fopenmp"],`
`    "nvcc": ["-std=c++14", "-O3", "--compiler-options=-fopenmp"],`
`}`
I got continuing errors certainly due to the incompatibility of the current code.
Could you provide me any hints on fixing these errors so I can use the extension with Pytorch 1.5?

**Comment by jpuigcerver** [comment]
Apologies for the delay, I've been quite busy. Finale, I made the project compatible with PyTorch 1.5.0.
