### ISSUE TITLE
Publishing wheels on PyPi

### ISSUE THREAD

**Issue by starride-teklia** [jpuigcerver/nnutils#8]
Hi Joan,

@La0 managed to build a matrix of pytorch/python version in CI and publish them on Gitlab PyPi registry : https://gitlab.com/teklia/atr/nnutils/-/packages

We would like to publish them on PyPi - there are two ways of doing that:
* we can update the [existing package](https://pypi.org/project/nnutils-pytorch/) if you provide us the credentials
* or we can create a new package under a different name (like pytorch-nnutils).

Can you tell us which solution you prefer?

Thanks,
Solène

**Comment by La0** [comment]
Side note: I currently only have CPU wheels from CI, I should have GPU by the end of the week but this require workers with GPU capabilities.

I don't think we will be able to run that on Github actions (for the GPU part), so we could configure our GItlab repo as a mirror of this one.

**Comment by jpuigcerver** [comment]
Hi all,

Thanks for your contributions. If you indicate a PyPi username, I can add
you as managers of the nnutils (and PyLaia) packages.

**Comment by La0** [comment]
You can add the user `teklia` (https://pypi.org/user/teklia/). Thanks !

**Comment by La0** [comment]
Hello @jpuigcerver ! Could you add the PyPi user `teklia` to both nnutils_pytorch & pylaia packages ? Thanks :smile:

**Comment by jpuigcerver** [comment]
I added you to nnutils_pytorch. There's no package for PyLaia, actually. I
was wrong.

**Comment by La0** [comment]
Thanks a lot !

**Comment by La0** [comment]
I was able to publish cpu & gpu wheels:
- https://pypi.org/project/nnutils-pytorch/
- https://pypi.org/project/nnutils-pytorch-cuda/

From this [CI build](https://gitlab.com/teklia/atr/nnutils/-/pipelines/710506057)
